apiVersion: v1
kind: Service
metadata:
  name: rate-api-service
  namespace: dynamic-pricing
  labels:
    app: rate-api
    component: external-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rate-api
