apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: dynamic-pricing
  labels:
    app: valkey
    component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: valkey
