name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: ./build.sh
    - name: Run the container
      run: ./dev.sh
    - name: Run all tests
      run: ./test.sh
    - name: Test API endpoint returns 200
      run: |
        echo "Testing API endpoint..."
        for i in {1..10}; do
          echo "Attempt $i/10: Testing pricing endpoint..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" 'http://localhost:3000/pricing?period=Summer&hotel=FloatingPointResort&room=SingletonRoom' || echo "000")
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ API endpoint returned HTTP 200"
            exit 0
          else
            echo "❌ API endpoint returned HTTP $HTTP_STATUS, retrying in 3 seconds..."
            sleep 3
          fi
        done
        echo "❌ API endpoint failed after 10 attempts"
        exit 1
